### ISSUE TITLE
Unhandled Exception - 'Access to the path is denied.'

### ISSUE THREAD

**Issue by 1joeljohnson** [Drommedhar/DlssUpdater#40] opened 2024-12-14 15:31 UTC
Encountered an unhandled exception: 
 ```System.IO.IOException: Access to the path '\\?\C:\Users\sjj2s\OneDrive\PCTweaks\DLSSUpdater\download' is denied.
   at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at DlssUpdater.Windows.Splashscreen.Splashscreen.OnContentRendered(EventArgs e) in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\Windows\Splashscreen\Splashscreen.xaml.cs:line 97
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)```

**Comment by Drommedhar** [comment] 2024-12-15 22:04
Duplicate of #30

**Closed by Drommedhar** 2024-12-15 22:04 UTC
Labels: bug
